// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: product.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/micrease/meshop-protos/header/pb"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ProductService service

func NewProductServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ProductService service

type ProductService interface {
	GetProductList(ctx context.Context, in *ProductRequest, opts ...client.CallOption) (*ProductListResponse, error)
	CreateProduct(ctx context.Context, in *Product, opts ...client.CallOption) (*ProductResponse, error)
	UpdateProduct(ctx context.Context, in *Product, opts ...client.CallOption) (*ProductResponse, error)
	DeleteProduct(ctx context.Context, in *Product, opts ...client.CallOption) (*ProductResponse, error)
	GetProductDetail(ctx context.Context, in *Product, opts ...client.CallOption) (*ProductResponse, error)
}

type productService struct {
	c    client.Client
	name string
}

func NewProductService(name string, c client.Client) ProductService {
	return &productService{
		c:    c,
		name: name,
	}
}

func (c *productService) GetProductList(ctx context.Context, in *ProductRequest, opts ...client.CallOption) (*ProductListResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.GetProductList", in)
	out := new(ProductListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) CreateProduct(ctx context.Context, in *Product, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.CreateProduct", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) UpdateProduct(ctx context.Context, in *Product, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.UpdateProduct", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) DeleteProduct(ctx context.Context, in *Product, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.DeleteProduct", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) GetProductDetail(ctx context.Context, in *Product, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.GetProductDetail", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductService service

type ProductServiceHandler interface {
	GetProductList(context.Context, *ProductRequest, *ProductListResponse) error
	CreateProduct(context.Context, *Product, *ProductResponse) error
	UpdateProduct(context.Context, *Product, *ProductResponse) error
	DeleteProduct(context.Context, *Product, *ProductResponse) error
	GetProductDetail(context.Context, *Product, *ProductResponse) error
}

func RegisterProductServiceHandler(s server.Server, hdlr ProductServiceHandler, opts ...server.HandlerOption) error {
	type productService interface {
		GetProductList(ctx context.Context, in *ProductRequest, out *ProductListResponse) error
		CreateProduct(ctx context.Context, in *Product, out *ProductResponse) error
		UpdateProduct(ctx context.Context, in *Product, out *ProductResponse) error
		DeleteProduct(ctx context.Context, in *Product, out *ProductResponse) error
		GetProductDetail(ctx context.Context, in *Product, out *ProductResponse) error
	}
	type ProductService struct {
		productService
	}
	h := &productServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ProductService{h}, opts...))
}

type productServiceHandler struct {
	ProductServiceHandler
}

func (h *productServiceHandler) GetProductList(ctx context.Context, in *ProductRequest, out *ProductListResponse) error {
	return h.ProductServiceHandler.GetProductList(ctx, in, out)
}

func (h *productServiceHandler) CreateProduct(ctx context.Context, in *Product, out *ProductResponse) error {
	return h.ProductServiceHandler.CreateProduct(ctx, in, out)
}

func (h *productServiceHandler) UpdateProduct(ctx context.Context, in *Product, out *ProductResponse) error {
	return h.ProductServiceHandler.UpdateProduct(ctx, in, out)
}

func (h *productServiceHandler) DeleteProduct(ctx context.Context, in *Product, out *ProductResponse) error {
	return h.ProductServiceHandler.DeleteProduct(ctx, in, out)
}

func (h *productServiceHandler) GetProductDetail(ctx context.Context, in *Product, out *ProductResponse) error {
	return h.ProductServiceHandler.GetProductDetail(ctx, in, out)
}
